### ISSUE TITLE
Install error: 'build/svgbob' doesn't exist

### ISSUE THREAD

**Issue by issakuss** [pandocker/pandocker-lua-filters#4]
Hello.
I found your amazing repository today and I would like to use them to write scientific papers.
However, unfortunately, your install instruction (i.e., pip install) didn't work for me.
It raised the error: `can't copy 'build/svgbob': doesn't exist or not a regular file`

It would be replicated via 
`docker run -it --rm python:latest sh $(pip install git+https://github.com/pandocker/pandocker-lua-filters.git)`
I ran this code on macOS (Apple Silicon).

I would appreciate it if you could give me a hint to solve this install problem.

**Comment by K4zuki** [comment]
Hello @issakuss, thank you for pointing it out. Yes, now direct pip install from repo is not working. I must update README file.

Can you try `pip install pandocker-lua-filters` instead? It has prebuilt binaries in package.

Though I am not sure these binaries (svgbob) run on Apple silicon.

**Comment by issakuss** [comment]
@K4zuki sama

Thank you for your reply.
`pip install pandocker-lua-filters` worked and I could install filters!
However, I couldn't use them due to the path(?) error: `removable-note.lua:20: module 'pandocker.utils' not found`

First, I tried simply `--lua-filter=removable-note.lua` option but it didn't find the filter.
So, I made a symbolic link: `ln -s ${HOME}/.local/share/lua/5.3/pandocker ${HOME}/.local/share/pandoc/filters` and the filter was applied.
But, it raised the error `removable-note.lua:20: module 'pandocker.utils' not found`

Could you let me know how can I solve this error?

**Comment by K4zuki** [comment]
Hello @issakuss ,

Does it change if **`ln -s ${HOME}/.local/share/lua/5.3 ${HOME}/.local/share/pandoc/filters`** and `pandoc -L pandocker/removable-note.lua`?
these filters are expecting to have `utils.lua` in `pandocker` directory.

**Comment by issakuss** [comment]
@K4zuki sama

I finally succeeded to run your code!
I found that my Lua version is inconsistent (Pandoc 2.18 use Lua ver 5.4 instead of 5.3), and this might cause the path error.

I tried the instructed command and additionally link lua/5.4 -> lua/5.3, and installed `lua-penlight` furthermore.

Now I enjoy your fantastic filters.
Thank you so much for your kind support.

**Comment by K4zuki** [comment]
@issakuss, it is great and much appreciated to hear you can use the filter.

**Comment by xiaotianxt** [comment]
Hello, today I encountered an error when trying to use your filters. Here is how to reproduce it:

1. I installed your filters using `pip install pandocker-lua-filters` with `lua 5.4` installed via `homebrew`.
2. I created a symbolic link from the `5.4` folder to the `filters` directory using `ln -s /opt/homebrew/Caskroom/miniforge/base/envs/py11/share/lua/5.4 filters`.
3. I ran `/opt/homebrew/bin/pandoc -L 5.4/pandocker/docx-extract-bullet-lists.lua test.md -o test.docx` and got the error `module 'pandocker.utils' not found`.

I'm not familiar with the lua runtime environment. I tried using `export LUA_PATH="$HOME/.local/share/pandoc/filters/?/?.lua;"` or `export LUA_PATH="$HOME/.local/share/pandoc/filters/?.lua;;"`, but still got the error `module 'pandocker.utils' not found`.

I don't know if you have any solutions to this. Thank you very much!

Update: I managed to use the filter by deleting all `require` syntax and hard code the logic 😭

**Comment by K4zuki** [comment]
Hello @xiaotianxt,

Did you try with full path?
I am not sure if pandoc builtin lua takes care of `LUA_PATH`. I never tried relative path myself.

If this continues, please clone the repository and copy stuff inside `lua/` to `filters` folder.

Hope this helps,
Kazuki/K4zuki
